version: "3.8"

services:
  frontend:
    build:
      context: ./task_management_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./task_management_backend
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    environment:
      - DATABASE_URL="postgres://task_management_backend:test_backend@db:5432/task_management"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-task_management_backend}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test_backend}
      POSTGRES_DB: ${POSTGRES_DB:-task_management}